language: ruby
rvm:
  - 2.4.0
  - 2.5.5
  - 2.6.3

before_install:
#  - gem update --system
  - gem install bundler
  -
script:
  - bundle install
  - bundle exec jekyll build

notifications:
  email: false

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  on:
    repo: MoralG/alejandro-mg.github.io
    on:
      branch: master
  fqdn: www.alejandro-mg.com